### ISSUE TITLE
Problems with Single Selection

### ISSUE THREAD

**Issue by idragon81** [dariopellegrini/FormBuilder#1]
When using single selection mode, if you try to change the value by clicking on the edittext it simply adds the new selection to the EditText making it act like Multiple Selection

We can fix it by replacing the pickDialog() Method with the following

 
       private void pickDialog(final EditText selectedEditText, final FormElement selectedFormElement) {
            this.selectedEditText = selectedEditText;
            AlertDialog.Builder builder = new AlertDialog.Builder(context);
            builder.setTitle("");
            builder.setSingleChoiceItems(selectedFormElement.getOptions().toArray(new CharSequence[selectedFormElement.getOptions().size()]), selectedFormElement.getCheckedValue(),     null);
            builder.setPositiveButton("OK", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialogInterface, int i) {
                    dialogInterface.dismiss();
                    int selectedPosition = ((AlertDialog) DialogInterface).getListView().getCheckedItemPosition();
                    String selectedElement = (selectedFormElement.getOptions().get(selectedPosition));
                    selectedFormElement.setValue(selectedElement);
                    selectedEditText.setText(selectedElement);
                }
            });
    
            builder.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialogInterface, int i) {
                    dialogInterface.dismiss();
                }
            });
            builder.show();
        }

**Comment by dariopellegrini** [comment]
Thanks. Updating within days.

**Comment by victorychain** [comment]
Not updated.

**Comment by shehabattia96** [comment]
Fixed in https://github.com/dariopellegrini/FormBuilder/pull/5
