### ISSUE TITLE
Required validation of SELECTION and MULTIPLE_SELECTION fails

### ISSUE THREAD

**Issue by danpalmer101** [dariopellegrini/FormBuilder#2]
If you set a `FormElement` of type `SELECTION` or `MULTIPLE_SELECTION` as `required`, it will always fail validation because `FormBuilder.validate()` checks the `value` field on the `FormElement` but not the `optionsSelected` field that is set for these types.

```
if (element.getRequired()) {
    // Should check optionsSelected if element.type == SELECTION or MULTIPLE_SELECTION
    if (element.getValue() == null || element.getValue().length() == 0) {
        isValid = false;
        if (view instanceof EditText) {
            ((EditText) view).setError(element.getErrorMessageOrDefault());
        }
    }
}
```

**Comment by dariopellegrini** [comment]
Should be solved, but still the EditText error is not visible. Working on that.
